server:
  port: 18080

spring:
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mbx?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
#    password:
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
#    sentinel:
#      master:
#      nodes:
    timeout: 0ms
  thymeleaf:
    cache: false
    mode: HTML5
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
mbx:
  version: '@project.version@'
  jwt:
    header: Authorization
    secret: Sixlab's Mbx
    expiration: 604800000
    bearer: Bearer|
  domain:
    sub:
      blog: ms
      lx: lx
      api: api
    escape: localhost,sixlab.cn,sixlab.com